// Produktinformation återgiven kortfattat från tumac.se. Se källor i varje produkt.
const PRODUCTS = [
  { id: 'mp85', title: 'Blandarpump MP85', category: 'pump', image: 'mp85.jpg', short: 'Kontinuerlig blandning och pumpning av puts och golvbruk.', description: 'MP85 kombinerar blandning och pumpning. Den är avsedd bland annat för självutjämnande golvspackel och bruk med hög lufthalt.', specs: [['Pumpmotor', '4 kW'], ['Vikt', '315 kg'], ['Mått (L × B × H)', '2480 × 890 × 1380 mm']], document: 'mp85.pdf', source: 'https://www.tumac.se/blandarpump-mp85/' },
  { id: 'p18', title: 'Putspump P18', category: 'pump', image: 'p18.jpg', short: 'En kompakt pump för puts och injektering.', description: 'P18 är en hjulförsedd putspump. Produktbladet beskriver slangval och utföranden för olika material.', specs: [['Vikt', '115 kg'], ['Behållarvolym', '70 liter'], ['Mått (L × B × H)', '1260 × 550 × 750 mm']], document: 'p18.pdf', source: 'https://www.tumac.se/Prod_blad/SV_P18.PDF' },
  { id: 'm100', title: 'Snabblandare M100', category: 'pump', image: 'm100.jpg', short: 'Satsblandare för puts, murbruk, betong och golvbruk.', description: 'M100 blandar satser om 100 liter. Den kan användas separat eller tillsammans med pumparna P50–P70. Tömningen sker pneumatiskt.', specs: [['Volym', '100 liter'], ['Motoreffekt', '3 kW'], ['Vikt', '205 kg']], source: 'https://www.tumac.se/produkt/m100/' },
  { id: 'p200', title: 'Betongpump P200', category: 'pump', image: 'p200.jpg', short: 'Skruvpump för pumpning av betong.', description: 'P200 är konstruerad för betong och material med hög densitet. Pumpen har två hastigheter och stödben för uppställning.', specs: [], document: 'p200.pdf', source: 'https://www.tumac.se/betong-p200/' },
  { id: 'p20', title: 'Putspump P20', category: 'pump', image: 'p20.jpg', short: 'Enfasmaskin med frekvensstyrning.', description: 'Läs produktbladet för P20 och kontakta Tumac för att få hjälp med rätt utförande för ditt material.', specs: [], document: 'p20.pdf', source: 'https://www.tumac.se/Prod_blad/SV_P20.PDF' },
  { id: 't2', title: 'Kranhiss T2', category: 'lift', image: 'kranhiss.jpg', short: 'Transport till kranhytten längs kranmasten.', description: 'T2 löper på en aluminiumgejder och hängs upp i en toppbalk. Kontakta Tumac för att diskutera din kran och montering.', specs: [['Maxlast enligt befintlig sida', '200 kg'], ['Lyfthastighet', '17 m/min']], source: 'https://www.tumac.se/fonsterputs/' },
  { id: 'nockspel', title: 'Nockspel', category: 'lift', image: 'nockspel.png', short: 'Ställningsspel för uppfordring av material.', description: 'För lyft av exempelvis ställningsrör och trävirke. Se dokumentet om modifiering och kontakta Tumac för aktuellt utförande.', specs: [], document: 'nockspel.pdf', documentLabel: 'Dokument om modifiering', source: 'https://www.tumac.se/nockspel/' },
  { id: 'liftcat', title: 'Fasadhiss Liftcat', category: 'lift', image: 'fasadhiss.jpg', short: 'Kundanpassad åtkomst för fasadunderhåll.', description: 'Liftcat bygger på ett skensystem för åtkomst längs fasader. Ta kontakt för att diskutera en lösning för byggnaden.', specs: [], source: 'https://www.tumac.se/coh-2001/' },
  { id: 'reservdelar', title: 'Reservdelar & tillbehör', category: 'parts', image: 'slang.jpg', short: 'Hitta rätt del till din Tumac-maskin.', description: 'Utgå från modell och serienummer när du söker reservdelar. Här finns en reservdelslista för P10–P20. Tumac hjälper dig att kontrollera rätt artikel.', specs: [], document: 'reservdelar.pdf', documentLabel: 'Reservdelslista P10–P20', source: 'https://www.tumac.se/Prod_blad/Reservdelslista_P10-P20.pdf' }
];
